language: node_js
node_js:
    - node
    - lts/*
install:
    - yarn install
script:
    - yarn lint
    - yarn build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: build
    on:
        branch: master
        node: 'lts/*'
